In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# load the dataset

dataset = pd.read_csv('grocery_item_transactions.csv')
dataset.head(3)

   item1 item2   item3   item4  item5 item6  item7
0  Chips  Coke    Eggs  Diaper  Bread   NaN    NaN
1  Bread  Coke     NaN     NaN    NaN   NaN    NaN
2   Eggs  Milk  Butter    Coke    NaN   NaN    NaN

In [5]:
# now create a new dataset (list of list) that only contains items not NaN

market = []

for i in range(0, dataset.shape[0]):
    cust = []
    for j in dataset.columns:
        if type(dataset[j][i]) == str:
            cust.append(dataset[j][i])
    market.append(cust)

In [6]:
# now get the most buy items

import collections

In [8]:
items = []
for i in market:
    for j in i:
        items.append(j)

collections.Counter(items)

Counter({'Beer': 524,
         'Chips': 506,
         'Butter': 497,
         'Milk': 493,
         'Coke': 492,
         'Eggs': 491,
         'Bread': 478,
         'Diaper': 476})

In [9]:
# now we need to figure out the association

from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [10]:
tr = TransactionEncoder()
tr.fit(market)

TransactionEncoder()

In [11]:
tr.transform(market)

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ..., False, False, False],
       [False, False,  True, ..., False,  True,  True],
       ...,
       [False, False,  True, ...,  True,  True, False],
       [False, False,  True, ..., False, False, False],
       [False,  True,  True, ..., False,  True,  True]])

In [12]:
df = pd.DataFrame(tr.transform(market), columns = tr.columns_)

In [13]:
# import fp growth
from mlxtend.frequent_patterns import fpgrowth

In [17]:
fpgrowth(df, min_support=0.05, use_colnames=True, max_len=3).sort_values(by=['support'], ascending=False)

    support               itemsets
7     0.524                 (Beer)
0     0.506                (Chips)
5     0.497               (Butter)
6     0.493                 (Milk)
1     0.492                 (Coke)
..      ...                    ...
68    0.110  (Bread, Eggs, Diaper)
51    0.110  (Bread, Butter, Milk)
46    0.109    (Bread, Coke, Milk)
69    0.104  (Bread, Coke, Diaper)
50    0.102  (Bread, Butter, Eggs)

[92 rows x 2 columns]

In [20]:
# now check the same without the max length
pd.set_option('display.max_rows', None)
fpgrowth(df, min_support=0.05, use_colnames=True).sort_values(by=['support'], ascending=True)

     support                        itemsets
78     0.050    (Bread, Chips, Butter, Eggs)
111    0.051   (Bread, Butter, Eggs, Diaper)
114    0.051     (Bread, Coke, Eggs, Diaper)
115    0.052   (Bread, Coke, Butter, Diaper)
131    0.052    (Coke, Butter, Milk, Diaper)
133    0.052   (Coke, Chips, Butter, Diaper)
121    0.052   (Bread, Butter, Milk, Diaper)
113    0.052    (Bread, Coke, Chips, Diaper)
110    0.052     (Bread, Diaper, Eggs, Beer)
21     0.052     (Coke, Chips, Butter, Milk)
116    0.052     (Bread, Coke, Milk, Diaper)
134    0.053   (Chips, Butter, Eggs, Diaper)
46     0.053     (Milk, Chips, Butter, Eggs)
69     0.053       (Bread, Coke, Milk, Eggs)
119    0.053  (Bread, Chips, Butter, Diaper)
67     0.054     (Bread, Coke, Butter, Eggs)
136    0.054   (Chips, Butter, Diaper, Beer)
66     0.055    (Bread, Coke, Chips, Butter)
135    0.055   (Chips, Butter, Milk, Diaper)
85     0.055       (Bread, Milk, Eggs, Beer)
145    0.056      (Milk, Diaper, Eggs, Beer)
146    0.056      (Coke, Diaper, Milk, Beer)
68     0.056       (Bread, Coke, Milk, Beer)
112    0.056     (Bread, Milk, Eggs, Diaper)
129    0.057    (Milk, Butter, Eggs, Diaper)
144    0.057     (Milk, Chips, Eggs, Diaper)
44     0.057      (Coke, Milk, Butter, Eggs)
137    0.058    (Diaper, Butter, Milk, Beer)
37     0.058     (Coke, Chips, Butter, Eggs)
77     0.058     (Bread, Butter, Eggs, Beer)
63     0.058      (Bread, Coke, Chips, Eggs)
120    0.058   (Bread, Diaper, Butter, Beer)
117    0.058     (Bread, Diaper, Milk, Beer)
109    0.058    (Bread, Chips, Eggs, Diaper)
101    0.059     (Coke, Chips, Eggs, Diaper)
147    0.059      (Coke, Milk, Eggs, Diaper)
130    0.059    (Coke, Diaper, Butter, Beer)
148    0.059     (Coke, Chips, Milk, Diaper)
86     0.060      (Bread, Milk, Chips, Eggs)
79     0.061    (Bread, Chips, Butter, Milk)
56     0.062      (Bread, Chips, Eggs, Beer)
138    0.062    (Diaper, Butter, Eggs, Beer)
43     0.062       (Coke, Milk, Chips, Eggs)
70     0.062      (Bread, Coke, Chips, Milk)
45     0.062      (Milk, Butter, Eggs, Beer)
80     0.062     (Bread, Butter, Milk, Beer)
118    0.062    (Bread, Chips, Diaper, Beer)
143    0.063     (Chips, Diaper, Milk, Beer)
20     0.063      (Coke, Butter, Milk, Beer)
102    0.063     (Coke, Chips, Diaper, Beer)
132    0.063    (Coke, Butter, Eggs, Diaper)
16     0.064     (Coke, Chips, Butter, Beer)
65     0.064     (Bread, Coke, Butter, Beer)
64     0.065      (Bread, Coke, Chips, Beer)
96     0.066     (Chips, Diaper, Eggs, Beer)
100    0.066      (Coke, Diaper, Eggs, Beer)
122    0.066    (Bread, Chips, Milk, Diaper)
157    0.066     (Chips, Butter, Milk, Beer)
36     0.067     (Chips, Butter, Eggs, Beer)
62     0.070       (Bread, Coke, Eggs, Beer)
47     0.072       (Milk, Chips, Eggs, Beer)
42     0.072        (Coke, Milk, Eggs, Beer)
76     0.072    (Bread, Chips, Butter, Beer)
22     0.073       (Coke, Chips, Milk, Beer)
84     0.077      (Bread, Chips, Milk, Beer)
31     0.079       (Coke, Chips, Eggs, Beer)
35     0.084      (Coke, Butter, Eggs, Beer)
74     0.102           (Bread, Butter, Eggs)
105    0.104           (Bread, Coke, Diaper)
61     0.109             (Bread, Coke, Milk)
107    0.110         (Bread, Butter, Diaper)
75     0.110           (Bread, Butter, Milk)
104    0.110           (Bread, Eggs, Diaper)
82     0.111             (Bread, Milk, Eggs)
60     0.111           (Bread, Coke, Butter)
106    0.113           (Bread, Diaper, Beer)
142    0.114            (Coke, Milk, Diaper)
17     0.114            (Coke, Butter, Milk)
108    0.115           (Bread, Milk, Diaper)
126    0.115         (Chips, Butter, Diaper)
125    0.115          (Coke, Butter, Diaper)
39     0.116            (Milk, Butter, Eggs)
98     0.116           (Coke, Chips, Diaper)
15     0.116           (Coke, Chips, Butter)
141    0.117            (Milk, Eggs, Diaper)
34     0.118           (Chips, Butter, Eggs)
99     0.118            (Coke, Diaper, Beer)
97     0.118            (Coke, Eggs, Diaper)
128    0.118          (Diaper, Butter, Beer)
140    0.119            (Diaper, Milk, Beer)
124    0.119          (Butter, Eggs, Diaper)
127    0.119          (Butter, Milk, Diaper)
94     0.120           (Chips, Eggs, Diaper)
58     0.120            (Bread, Coke, Chips)
57     0.120             (Bread, Coke, Eggs)
54     0.121            (Bread, Chips, Eggs)
55     0.121             (Bread, Eggs, Beer)
103    0.123          (Bread, Chips, Diaper)
38     0.123              (Coke, Milk, Eggs)
139    0.124           (Chips, Milk, Diaper)
41     0.124             (Milk, Chips, Eggs)
123    0.125           (Chips, Diaper, Beer)
155    0.125           (Chips, Butter, Milk)
59     0.127             (Bread, Coke, Beer)
19     0.127             (Coke, Chips, Milk)
95     0.127            (Diaper, Eggs, Beer)
73     0.128          (Bread, Chips, Butter)
32     0.128            (Coke, Butter, Eggs)
81     0.129             (Bread, Milk, Beer)
29     0.129             (Coke, Chips, Eggs)
72     0.131           (Bread, Butter, Beer)
151    0.131           (Chips, Butter, Beer)
40     0.132              (Milk, Eggs, Beer)
83     0.135            (Bread, Chips, Milk)
156    0.135            (Butter, Milk, Beer)
14     0.137            (Coke, Butter, Beer)
18     0.138              (Coke, Milk, Beer)
13     0.141             (Coke, Chips, Beer)
71     0.141            (Bread, Chips, Beer)
30     0.141             (Chips, Eggs, Beer)
158    0.142             (Chips, Milk, Beer)
33     0.143            (Butter, Eggs, Beer)
28     0.155              (Coke, Eggs, Beer)
90     0.227                 (Bread, Diaper)
92     0.230                (Butter, Diaper)
50     0.230                   (Bread, Coke)
52     0.230                 (Bread, Butter)
93     0.232                  (Milk, Diaper)
53     0.233                   (Bread, Milk)
49     0.234                   (Bread, Eggs)
89     0.234                  (Coke, Diaper)
88     0.236                  (Eggs, Diaper)
11     0.238                    (Coke, Milk)
91     0.240                  (Diaper, Beer)
10     0.241                  (Coke, Butter)
26     0.241                    (Milk, Eggs)
87     0.243                 (Chips, Diaper)
152    0.243                  (Butter, Milk)
25     0.243                  (Butter, Eggs)
24     0.244                   (Chips, Eggs)
9      0.246                   (Coke, Chips)
51     0.247                   (Bread, Beer)
23     0.251                    (Coke, Eggs)
150    0.255                 (Chips, Butter)
48     0.260                  (Bread, Chips)
154    0.260                   (Chips, Milk)
8      0.262                   (Chips, Beer)
149    0.269                  (Butter, Beer)
12     0.270                    (Coke, Beer)
27     0.271                    (Eggs, Beer)
153    0.275                    (Milk, Beer)
4      0.476                        (Diaper)
3      0.478                         (Bread)
2      0.491                          (Eggs)
1      0.492                          (Coke)
6      0.493                          (Milk)
5      0.497                        (Butter)
0      0.506                         (Chips)
7      0.524                          (Beer)

In [21]:
# now display all the values which are above 0.05
fpgrowth(df, min_support=0.05, use_colnames=True).sort_values(by=['support'], ascending=True).query('support > 0.05')

     support                        itemsets
111    0.051   (Bread, Butter, Eggs, Diaper)
114    0.051     (Bread, Coke, Eggs, Diaper)
115    0.052   (Bread, Coke, Butter, Diaper)
131    0.052    (Coke, Butter, Milk, Diaper)
133    0.052   (Coke, Chips, Butter, Diaper)
121    0.052   (Bread, Butter, Milk, Diaper)
113    0.052    (Bread, Coke, Chips, Diaper)
110    0.052     (Bread, Diaper, Eggs, Beer)
21     0.052     (Coke, Chips, Butter, Milk)
116    0.052     (Bread, Coke, Milk, Diaper)
134    0.053   (Chips, Butter, Eggs, Diaper)
46     0.053     (Milk, Chips, Butter, Eggs)
69     0.053       (Bread, Coke, Milk, Eggs)
119    0.053  (Bread, Chips, Butter, Diaper)
67     0.054     (Bread, Coke, Butter, Eggs)
136    0.054   (Chips, Butter, Diaper, Beer)
66     0.055    (Bread, Coke, Chips, Butter)
135    0.055   (Chips, Butter, Milk, Diaper)
85     0.055       (Bread, Milk, Eggs, Beer)
145    0.056      (Milk, Diaper, Eggs, Beer)
146    0.056      (Coke, Diaper, Milk, Beer)
68     0.056       (Bread, Coke, Milk, Beer)
112    0.056     (Bread, Milk, Eggs, Diaper)
129    0.057    (Milk, Butter, Eggs, Diaper)
144    0.057     (Milk, Chips, Eggs, Diaper)
44     0.057      (Coke, Milk, Butter, Eggs)
137    0.058    (Diaper, Butter, Milk, Beer)
37     0.058     (Coke, Chips, Butter, Eggs)
77     0.058     (Bread, Butter, Eggs, Beer)
63     0.058      (Bread, Coke, Chips, Eggs)
120    0.058   (Bread, Diaper, Butter, Beer)
117    0.058     (Bread, Diaper, Milk, Beer)
109    0.058    (Bread, Chips, Eggs, Diaper)
101    0.059     (Coke, Chips, Eggs, Diaper)
147    0.059      (Coke, Milk, Eggs, Diaper)
130    0.059    (Coke, Diaper, Butter, Beer)
148    0.059     (Coke, Chips, Milk, Diaper)
86     0.060      (Bread, Milk, Chips, Eggs)
79     0.061    (Bread, Chips, Butter, Milk)
56     0.062      (Bread, Chips, Eggs, Beer)
138    0.062    (Diaper, Butter, Eggs, Beer)
43     0.062       (Coke, Milk, Chips, Eggs)
70     0.062      (Bread, Coke, Chips, Milk)
45     0.062      (Milk, Butter, Eggs, Beer)
80     0.062     (Bread, Butter, Milk, Beer)
118    0.062    (Bread, Chips, Diaper, Beer)
143    0.063     (Chips, Diaper, Milk, Beer)
20     0.063      (Coke, Butter, Milk, Beer)
102    0.063     (Coke, Chips, Diaper, Beer)
132    0.063    (Coke, Butter, Eggs, Diaper)
16     0.064     (Coke, Chips, Butter, Beer)
65     0.064     (Bread, Coke, Butter, Beer)
64     0.065      (Bread, Coke, Chips, Beer)
96     0.066     (Chips, Diaper, Eggs, Beer)
100    0.066      (Coke, Diaper, Eggs, Beer)
122    0.066    (Bread, Chips, Milk, Diaper)
157    0.066     (Chips, Butter, Milk, Beer)
36     0.067     (Chips, Butter, Eggs, Beer)
62     0.070       (Bread, Coke, Eggs, Beer)
47     0.072       (Milk, Chips, Eggs, Beer)
42     0.072        (Coke, Milk, Eggs, Beer)
76     0.072    (Bread, Chips, Butter, Beer)
22     0.073       (Coke, Chips, Milk, Beer)
84     0.077      (Bread, Chips, Milk, Beer)
31     0.079       (Coke, Chips, Eggs, Beer)
35     0.084      (Coke, Butter, Eggs, Beer)
74     0.102           (Bread, Butter, Eggs)
105    0.104           (Bread, Coke, Diaper)
61     0.109             (Bread, Coke, Milk)
107    0.110         (Bread, Butter, Diaper)
75     0.110           (Bread, Butter, Milk)
104    0.110           (Bread, Eggs, Diaper)
82     0.111             (Bread, Milk, Eggs)
60     0.111           (Bread, Coke, Butter)
106    0.113           (Bread, Diaper, Beer)
142    0.114            (Coke, Milk, Diaper)
17     0.114            (Coke, Butter, Milk)
108    0.115           (Bread, Milk, Diaper)
126    0.115         (Chips, Butter, Diaper)
125    0.115          (Coke, Butter, Diaper)
39     0.116            (Milk, Butter, Eggs)
98     0.116           (Coke, Chips, Diaper)
15     0.116           (Coke, Chips, Butter)
141    0.117            (Milk, Eggs, Diaper)
34     0.118           (Chips, Butter, Eggs)
99     0.118            (Coke, Diaper, Beer)
97     0.118            (Coke, Eggs, Diaper)
128    0.118          (Diaper, Butter, Beer)
140    0.119            (Diaper, Milk, Beer)
124    0.119          (Butter, Eggs, Diaper)
127    0.119          (Butter, Milk, Diaper)
94     0.120           (Chips, Eggs, Diaper)
58     0.120            (Bread, Coke, Chips)
57     0.120             (Bread, Coke, Eggs)
54     0.121            (Bread, Chips, Eggs)
55     0.121             (Bread, Eggs, Beer)
103    0.123          (Bread, Chips, Diaper)
38     0.123              (Coke, Milk, Eggs)
139    0.124           (Chips, Milk, Diaper)
41     0.124             (Milk, Chips, Eggs)
123    0.125           (Chips, Diaper, Beer)
155    0.125           (Chips, Butter, Milk)
59     0.127             (Bread, Coke, Beer)
19     0.127             (Coke, Chips, Milk)
95     0.127            (Diaper, Eggs, Beer)
73     0.128          (Bread, Chips, Butter)
32     0.128            (Coke, Butter, Eggs)
81     0.129             (Bread, Milk, Beer)
29     0.129             (Coke, Chips, Eggs)
72     0.131           (Bread, Butter, Beer)
151    0.131           (Chips, Butter, Beer)
40     0.132              (Milk, Eggs, Beer)
83     0.135            (Bread, Chips, Milk)
156    0.135            (Butter, Milk, Beer)
14     0.137            (Coke, Butter, Beer)
18     0.138              (Coke, Milk, Beer)
13     0.141             (Coke, Chips, Beer)
71     0.141            (Bread, Chips, Beer)
30     0.141             (Chips, Eggs, Beer)
158    0.142             (Chips, Milk, Beer)
33     0.143            (Butter, Eggs, Beer)
28     0.155              (Coke, Eggs, Beer)
90     0.227                 (Bread, Diaper)
92     0.230                (Butter, Diaper)
50     0.230                   (Bread, Coke)
52     0.230                 (Bread, Butter)
93     0.232                  (Milk, Diaper)
53     0.233                   (Bread, Milk)
49     0.234                   (Bread, Eggs)
89     0.234                  (Coke, Diaper)
88     0.236                  (Eggs, Diaper)
11     0.238                    (Coke, Milk)
91     0.240                  (Diaper, Beer)
10     0.241                  (Coke, Butter)
26     0.241                    (Milk, Eggs)
87     0.243                 (Chips, Diaper)
152    0.243                  (Butter, Milk)
25     0.243                  (Butter, Eggs)
24     0.244                   (Chips, Eggs)
9      0.246                   (Coke, Chips)
51     0.247                   (Bread, Beer)
23     0.251                    (Coke, Eggs)
150    0.255                 (Chips, Butter)
48     0.260                  (Bread, Chips)
154    0.260                   (Chips, Milk)
8      0.262                   (Chips, Beer)
149    0.269                  (Butter, Beer)
12     0.270                    (Coke, Beer)
27     0.271                    (Eggs, Beer)
153    0.275                    (Milk, Beer)
4      0.476                        (Diaper)
3      0.478                         (Bread)
2      0.491                          (Eggs)
1      0.492                          (Coke)
6      0.493                          (Milk)
5      0.497                        (Butter)
0      0.506                         (Chips)
7      0.524                          (Beer)